/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { FilterCategory } from "./components/rui-filter-chips/rui-filter-chips";
import { MealPlan } from "./components/rui-meal-planner/rui-meal-planner";
import { RecipeSummary } from "./components/rui-recipe-card/rui-recipe-card";
import { RecipeSummary as RecipeSummary1 } from "./components/rui-recipe-card/rui-recipe-card";
import { RecipeFull } from "./components/rui-recipe-detail/rui-recipe-detail";
export { FilterCategory } from "./components/rui-filter-chips/rui-filter-chips";
export { MealPlan } from "./components/rui-meal-planner/rui-meal-planner";
export { RecipeSummary } from "./components/rui-recipe-card/rui-recipe-card";
export { RecipeSummary as RecipeSummary1 } from "./components/rui-recipe-card/rui-recipe-card";
export { RecipeFull } from "./components/rui-recipe-detail/rui-recipe-detail";
export namespace Components {
    /**
     * Shared button primitive with variants.
     */
    interface RuiButton {
        /**
          * Disabled state.
          * @default false
         */
        "disabled": boolean;
        /**
          * Loading state (shows spinner, disables interaction).
          * @default false
         */
        "loading": boolean;
        /**
          * Native button type.
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Button variant.
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'danger' | 'ghost';
    }
    /**
     * Filter chips for category selection (multi-select).
     */
    interface RuiFilterChips {
        /**
          * Available categories.
          * @default []
         */
        "categories": FilterCategory[];
        /**
          * Currently selected category values.
          * @default []
         */
        "selected": string[];
    }
    /**
     * Weekly meal planner. Renders one row per day with assign/remove/clear actions.
     */
    interface RuiMealPlanner {
        /**
          * Days of the week to render.
          * @default [     'Monday',     'Tuesday',     'Wednesday',     'Thursday',     'Friday',     'Saturday',     'Sunday',   ]
         */
        "days": string[];
        /**
          * Map of day -> PlannedMeal (or null when empty).
          * @default {}
         */
        "plan": MealPlan;
    }
    /**
     * Modal dialog with default + footer slots.
     */
    interface RuiModal {
        /**
          * Close on backdrop click.
          * @default true
         */
        "closeOnBackdrop": boolean;
        /**
          * Modal title.
          * @default ''
         */
        "modalTitle": string;
        /**
          * Whether the modal is open.
          * @default false
         */
        "open": boolean;
    }
    /**
     * Recipe card. Displays summary info and a favorite toggle.
     */
    interface RuiRecipeCard {
        /**
          * Whether this recipe is favorited.
          * @default false
         */
        "isFavorite": boolean;
        /**
          * Recipe summary object.
         */
        "recipe": RecipeSummary1;
    }
    /**
     * Full recipe detail view: image, meta, ingredients, instructions.
     */
    interface RuiRecipeDetail {
        /**
          * Whether the recipe is favorited.
          * @default false
         */
        "isFavorite": boolean;
        /**
          * Full recipe object.
         */
        "recipe": RecipeFull;
    }
    /**
     * Responsive grid of recipe cards. Re-renders cards when recipes/favorites change.
     */
    interface RuiRecipeList {
        /**
          * Empty-state message.
          * @default 'No recipes found.'
         */
        "emptyMessage": string;
        /**
          * Array of favorite recipe ids (used to mark cards as favorite).
          * @default []
         */
        "favorites": string[];
        /**
          * Array of recipe summaries to display.
          * @default []
         */
        "recipes": RecipeSummary[];
    }
    /**
     * Search bar with debounced input + submit events.
     */
    interface RuiSearchBar {
        /**
          * Debounce delay in ms for ruiSearchInput.
          * @default 300
         */
        "debounceMs": number;
        /**
          * Placeholder text.
          * @default 'Search recipes...'
         */
        "placeholder": string;
        /**
          * Current input value.
          * @default ''
         */
        "value": string;
    }
}
export interface RuiButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRuiButtonElement;
}
export interface RuiFilterChipsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRuiFilterChipsElement;
}
export interface RuiMealPlannerCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRuiMealPlannerElement;
}
export interface RuiModalCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRuiModalElement;
}
export interface RuiRecipeCardCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRuiRecipeCardElement;
}
export interface RuiRecipeDetailCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRuiRecipeDetailElement;
}
export interface RuiRecipeListCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRuiRecipeListElement;
}
export interface RuiSearchBarCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLRuiSearchBarElement;
}
declare global {
    interface HTMLRuiButtonElementEventMap {
        "ruiClick": MouseEvent;
    }
    /**
     * Shared button primitive with variants.
     */
    interface HTMLRuiButtonElement extends Components.RuiButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRuiButtonElementEventMap>(type: K, listener: (this: HTMLRuiButtonElement, ev: RuiButtonCustomEvent<HTMLRuiButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRuiButtonElementEventMap>(type: K, listener: (this: HTMLRuiButtonElement, ev: RuiButtonCustomEvent<HTMLRuiButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRuiButtonElement: {
        prototype: HTMLRuiButtonElement;
        new (): HTMLRuiButtonElement;
    };
    interface HTMLRuiFilterChipsElementEventMap {
        "ruiFilterChange": string[];
    }
    /**
     * Filter chips for category selection (multi-select).
     */
    interface HTMLRuiFilterChipsElement extends Components.RuiFilterChips, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRuiFilterChipsElementEventMap>(type: K, listener: (this: HTMLRuiFilterChipsElement, ev: RuiFilterChipsCustomEvent<HTMLRuiFilterChipsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRuiFilterChipsElementEventMap>(type: K, listener: (this: HTMLRuiFilterChipsElement, ev: RuiFilterChipsCustomEvent<HTMLRuiFilterChipsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRuiFilterChipsElement: {
        prototype: HTMLRuiFilterChipsElement;
        new (): HTMLRuiFilterChipsElement;
    };
    interface HTMLRuiMealPlannerElementEventMap {
        "ruiAssignMeal": { day: string };
        "ruiRemoveMeal": { day: string; recipe: RecipeSummary };
        "ruiClearDay": { day: string };
        "ruiSelectMeal": { day: string; recipe: RecipeSummary };
    }
    /**
     * Weekly meal planner. Renders one row per day with assign/remove/clear actions.
     */
    interface HTMLRuiMealPlannerElement extends Components.RuiMealPlanner, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRuiMealPlannerElementEventMap>(type: K, listener: (this: HTMLRuiMealPlannerElement, ev: RuiMealPlannerCustomEvent<HTMLRuiMealPlannerElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRuiMealPlannerElementEventMap>(type: K, listener: (this: HTMLRuiMealPlannerElement, ev: RuiMealPlannerCustomEvent<HTMLRuiMealPlannerElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRuiMealPlannerElement: {
        prototype: HTMLRuiMealPlannerElement;
        new (): HTMLRuiMealPlannerElement;
    };
    interface HTMLRuiModalElementEventMap {
        "ruiClose": void;
    }
    /**
     * Modal dialog with default + footer slots.
     */
    interface HTMLRuiModalElement extends Components.RuiModal, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRuiModalElementEventMap>(type: K, listener: (this: HTMLRuiModalElement, ev: RuiModalCustomEvent<HTMLRuiModalElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRuiModalElementEventMap>(type: K, listener: (this: HTMLRuiModalElement, ev: RuiModalCustomEvent<HTMLRuiModalElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRuiModalElement: {
        prototype: HTMLRuiModalElement;
        new (): HTMLRuiModalElement;
    };
    interface HTMLRuiRecipeCardElementEventMap {
        "ruiCardClick": RecipeSummary1;
        "ruiFavoriteToggle": { recipe: RecipeSummary1; isFavorite: boolean };
    }
    /**
     * Recipe card. Displays summary info and a favorite toggle.
     */
    interface HTMLRuiRecipeCardElement extends Components.RuiRecipeCard, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRuiRecipeCardElementEventMap>(type: K, listener: (this: HTMLRuiRecipeCardElement, ev: RuiRecipeCardCustomEvent<HTMLRuiRecipeCardElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRuiRecipeCardElementEventMap>(type: K, listener: (this: HTMLRuiRecipeCardElement, ev: RuiRecipeCardCustomEvent<HTMLRuiRecipeCardElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRuiRecipeCardElement: {
        prototype: HTMLRuiRecipeCardElement;
        new (): HTMLRuiRecipeCardElement;
    };
    interface HTMLRuiRecipeDetailElementEventMap {
        "ruiAddToPlan": RecipeFull;
        "ruiFavoriteToggle": { recipe: RecipeFull; isFavorite: boolean };
    }
    /**
     * Full recipe detail view: image, meta, ingredients, instructions.
     */
    interface HTMLRuiRecipeDetailElement extends Components.RuiRecipeDetail, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRuiRecipeDetailElementEventMap>(type: K, listener: (this: HTMLRuiRecipeDetailElement, ev: RuiRecipeDetailCustomEvent<HTMLRuiRecipeDetailElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRuiRecipeDetailElementEventMap>(type: K, listener: (this: HTMLRuiRecipeDetailElement, ev: RuiRecipeDetailCustomEvent<HTMLRuiRecipeDetailElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRuiRecipeDetailElement: {
        prototype: HTMLRuiRecipeDetailElement;
        new (): HTMLRuiRecipeDetailElement;
    };
    interface HTMLRuiRecipeListElementEventMap {
        "ruiSelectRecipe": RecipeSummary;
        "ruiFavoriteToggle": { recipe: RecipeSummary; isFavorite: boolean };
    }
    /**
     * Responsive grid of recipe cards. Re-renders cards when recipes/favorites change.
     */
    interface HTMLRuiRecipeListElement extends Components.RuiRecipeList, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRuiRecipeListElementEventMap>(type: K, listener: (this: HTMLRuiRecipeListElement, ev: RuiRecipeListCustomEvent<HTMLRuiRecipeListElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRuiRecipeListElementEventMap>(type: K, listener: (this: HTMLRuiRecipeListElement, ev: RuiRecipeListCustomEvent<HTMLRuiRecipeListElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRuiRecipeListElement: {
        prototype: HTMLRuiRecipeListElement;
        new (): HTMLRuiRecipeListElement;
    };
    interface HTMLRuiSearchBarElementEventMap {
        "ruiSearchInput": string;
        "ruiSearchSubmit": string;
    }
    /**
     * Search bar with debounced input + submit events.
     */
    interface HTMLRuiSearchBarElement extends Components.RuiSearchBar, HTMLStencilElement {
        addEventListener<K extends keyof HTMLRuiSearchBarElementEventMap>(type: K, listener: (this: HTMLRuiSearchBarElement, ev: RuiSearchBarCustomEvent<HTMLRuiSearchBarElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLRuiSearchBarElementEventMap>(type: K, listener: (this: HTMLRuiSearchBarElement, ev: RuiSearchBarCustomEvent<HTMLRuiSearchBarElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLRuiSearchBarElement: {
        prototype: HTMLRuiSearchBarElement;
        new (): HTMLRuiSearchBarElement;
    };
    interface HTMLElementTagNameMap {
        "rui-button": HTMLRuiButtonElement;
        "rui-filter-chips": HTMLRuiFilterChipsElement;
        "rui-meal-planner": HTMLRuiMealPlannerElement;
        "rui-modal": HTMLRuiModalElement;
        "rui-recipe-card": HTMLRuiRecipeCardElement;
        "rui-recipe-detail": HTMLRuiRecipeDetailElement;
        "rui-recipe-list": HTMLRuiRecipeListElement;
        "rui-search-bar": HTMLRuiSearchBarElement;
    }
}
declare namespace LocalJSX {
    /**
     * Shared button primitive with variants.
     */
    interface RuiButton {
        /**
          * Disabled state.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Loading state (shows spinner, disables interaction).
          * @default false
         */
        "loading"?: boolean;
        /**
          * Emitted on click (bubbles/composed for cross-boundary listening).
         */
        "onRuiClick"?: (event: RuiButtonCustomEvent<MouseEvent>) => void;
        /**
          * Native button type.
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Button variant.
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'danger' | 'ghost';
    }
    /**
     * Filter chips for category selection (multi-select).
     */
    interface RuiFilterChips {
        /**
          * Available categories.
          * @default []
         */
        "categories"?: FilterCategory[];
        /**
          * Emitted when the selection changes. detail: string[] (selected values).
         */
        "onRuiFilterChange"?: (event: RuiFilterChipsCustomEvent<string[]>) => void;
        /**
          * Currently selected category values.
          * @default []
         */
        "selected"?: string[];
    }
    /**
     * Weekly meal planner. Renders one row per day with assign/remove/clear actions.
     */
    interface RuiMealPlanner {
        /**
          * Days of the week to render.
          * @default [     'Monday',     'Tuesday',     'Wednesday',     'Thursday',     'Friday',     'Saturday',     'Sunday',   ]
         */
        "days"?: string[];
        /**
          * Emitted when "Assign" is clicked. detail: { day }.
         */
        "onRuiAssignMeal"?: (event: RuiMealPlannerCustomEvent<{ day: string }>) => void;
        /**
          * Emitted when "Clear" is clicked for a day. detail: { day }.
         */
        "onRuiClearDay"?: (event: RuiMealPlannerCustomEvent<{ day: string }>) => void;
        /**
          * Emitted when "Remove" is clicked on a planned meal. detail: { day, recipe }.
         */
        "onRuiRemoveMeal"?: (event: RuiMealPlannerCustomEvent<{ day: string; recipe: RecipeSummary }>) => void;
        /**
          * Emitted when a planned meal is clicked to view recipe. detail: { day, recipe }.
         */
        "onRuiSelectMeal"?: (event: RuiMealPlannerCustomEvent<{ day: string; recipe: RecipeSummary }>) => void;
        /**
          * Map of day -> PlannedMeal (or null when empty).
          * @default {}
         */
        "plan"?: MealPlan;
    }
    /**
     * Modal dialog with default + footer slots.
     */
    interface RuiModal {
        /**
          * Close on backdrop click.
          * @default true
         */
        "closeOnBackdrop"?: boolean;
        /**
          * Modal title.
          * @default ''
         */
        "modalTitle"?: string;
        /**
          * Emitted when the modal requests to close (X button, backdrop, Escape).
         */
        "onRuiClose"?: (event: RuiModalCustomEvent<void>) => void;
        /**
          * Whether the modal is open.
          * @default false
         */
        "open"?: boolean;
    }
    /**
     * Recipe card. Displays summary info and a favorite toggle.
     */
    interface RuiRecipeCard {
        /**
          * Whether this recipe is favorited.
          * @default false
         */
        "isFavorite"?: boolean;
        /**
          * Emitted when the card body is clicked. detail: RecipeSummary.
         */
        "onRuiCardClick"?: (event: RuiRecipeCardCustomEvent<RecipeSummary1>) => void;
        /**
          * Emitted when the favorite heart is toggled. detail: { recipe, isFavorite }.
         */
        "onRuiFavoriteToggle"?: (event: RuiRecipeCardCustomEvent<{ recipe: RecipeSummary1; isFavorite: boolean }>) => void;
        /**
          * Recipe summary object.
         */
        "recipe": RecipeSummary1;
    }
    /**
     * Full recipe detail view: image, meta, ingredients, instructions.
     */
    interface RuiRecipeDetail {
        /**
          * Whether the recipe is favorited.
          * @default false
         */
        "isFavorite"?: boolean;
        /**
          * Emitted when "Add to plan" is clicked. detail: RecipeFull.
         */
        "onRuiAddToPlan"?: (event: RuiRecipeDetailCustomEvent<RecipeFull>) => void;
        /**
          * Emitted when the favorite toggle is clicked. detail: { recipe, isFavorite }.
         */
        "onRuiFavoriteToggle"?: (event: RuiRecipeDetailCustomEvent<{ recipe: RecipeFull; isFavorite: boolean }>) => void;
        /**
          * Full recipe object.
         */
        "recipe": RecipeFull;
    }
    /**
     * Responsive grid of recipe cards. Re-renders cards when recipes/favorites change.
     */
    interface RuiRecipeList {
        /**
          * Empty-state message.
          * @default 'No recipes found.'
         */
        "emptyMessage"?: string;
        /**
          * Array of favorite recipe ids (used to mark cards as favorite).
          * @default []
         */
        "favorites"?: string[];
        /**
          * Emitted when a favorite is toggled from a card. detail: { recipe, isFavorite }.
         */
        "onRuiFavoriteToggle"?: (event: RuiRecipeListCustomEvent<{ recipe: RecipeSummary; isFavorite: boolean }>) => void;
        /**
          * Emitted when a card is clicked. detail: RecipeSummary.
         */
        "onRuiSelectRecipe"?: (event: RuiRecipeListCustomEvent<RecipeSummary>) => void;
        /**
          * Array of recipe summaries to display.
          * @default []
         */
        "recipes"?: RecipeSummary[];
    }
    /**
     * Search bar with debounced input + submit events.
     */
    interface RuiSearchBar {
        /**
          * Debounce delay in ms for ruiSearchInput.
          * @default 300
         */
        "debounceMs"?: number;
        /**
          * Emitted (debounced) on input. detail: string.
         */
        "onRuiSearchInput"?: (event: RuiSearchBarCustomEvent<string>) => void;
        /**
          * Emitted on submit (Enter or button). detail: string.
         */
        "onRuiSearchSubmit"?: (event: RuiSearchBarCustomEvent<string>) => void;
        /**
          * Placeholder text.
          * @default 'Search recipes...'
         */
        "placeholder"?: string;
        /**
          * Current input value.
          * @default ''
         */
        "value"?: string;
    }

    interface RuiButtonAttributes {
        "variant": 'primary' | 'secondary' | 'danger' | 'ghost';
        "disabled": boolean;
        "loading": boolean;
        "type": 'button' | 'submit' | 'reset';
    }
    interface RuiModalAttributes {
        "open": boolean;
        "modalTitle": string;
        "closeOnBackdrop": boolean;
    }
    interface RuiRecipeCardAttributes {
        "isFavorite": boolean;
    }
    interface RuiRecipeDetailAttributes {
        "isFavorite": boolean;
    }
    interface RuiRecipeListAttributes {
        "emptyMessage": string;
    }
    interface RuiSearchBarAttributes {
        "value": string;
        "placeholder": string;
        "debounceMs": number;
    }

    interface IntrinsicElements {
        "rui-button": Omit<RuiButton, keyof RuiButtonAttributes> & { [K in keyof RuiButton & keyof RuiButtonAttributes]?: RuiButton[K] } & { [K in keyof RuiButton & keyof RuiButtonAttributes as `attr:${K}`]?: RuiButtonAttributes[K] } & { [K in keyof RuiButton & keyof RuiButtonAttributes as `prop:${K}`]?: RuiButton[K] };
        "rui-filter-chips": RuiFilterChips;
        "rui-meal-planner": RuiMealPlanner;
        "rui-modal": Omit<RuiModal, keyof RuiModalAttributes> & { [K in keyof RuiModal & keyof RuiModalAttributes]?: RuiModal[K] } & { [K in keyof RuiModal & keyof RuiModalAttributes as `attr:${K}`]?: RuiModalAttributes[K] } & { [K in keyof RuiModal & keyof RuiModalAttributes as `prop:${K}`]?: RuiModal[K] };
        "rui-recipe-card": Omit<RuiRecipeCard, keyof RuiRecipeCardAttributes> & { [K in keyof RuiRecipeCard & keyof RuiRecipeCardAttributes]?: RuiRecipeCard[K] } & { [K in keyof RuiRecipeCard & keyof RuiRecipeCardAttributes as `attr:${K}`]?: RuiRecipeCardAttributes[K] } & { [K in keyof RuiRecipeCard & keyof RuiRecipeCardAttributes as `prop:${K}`]?: RuiRecipeCard[K] };
        "rui-recipe-detail": Omit<RuiRecipeDetail, keyof RuiRecipeDetailAttributes> & { [K in keyof RuiRecipeDetail & keyof RuiRecipeDetailAttributes]?: RuiRecipeDetail[K] } & { [K in keyof RuiRecipeDetail & keyof RuiRecipeDetailAttributes as `attr:${K}`]?: RuiRecipeDetailAttributes[K] } & { [K in keyof RuiRecipeDetail & keyof RuiRecipeDetailAttributes as `prop:${K}`]?: RuiRecipeDetail[K] };
        "rui-recipe-list": Omit<RuiRecipeList, keyof RuiRecipeListAttributes> & { [K in keyof RuiRecipeList & keyof RuiRecipeListAttributes]?: RuiRecipeList[K] } & { [K in keyof RuiRecipeList & keyof RuiRecipeListAttributes as `attr:${K}`]?: RuiRecipeListAttributes[K] } & { [K in keyof RuiRecipeList & keyof RuiRecipeListAttributes as `prop:${K}`]?: RuiRecipeList[K] };
        "rui-search-bar": Omit<RuiSearchBar, keyof RuiSearchBarAttributes> & { [K in keyof RuiSearchBar & keyof RuiSearchBarAttributes]?: RuiSearchBar[K] } & { [K in keyof RuiSearchBar & keyof RuiSearchBarAttributes as `attr:${K}`]?: RuiSearchBarAttributes[K] } & { [K in keyof RuiSearchBar & keyof RuiSearchBarAttributes as `prop:${K}`]?: RuiSearchBar[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * Shared button primitive with variants.
             */
            "rui-button": LocalJSX.IntrinsicElements["rui-button"] & JSXBase.HTMLAttributes<HTMLRuiButtonElement>;
            /**
             * Filter chips for category selection (multi-select).
             */
            "rui-filter-chips": LocalJSX.IntrinsicElements["rui-filter-chips"] & JSXBase.HTMLAttributes<HTMLRuiFilterChipsElement>;
            /**
             * Weekly meal planner. Renders one row per day with assign/remove/clear actions.
             */
            "rui-meal-planner": LocalJSX.IntrinsicElements["rui-meal-planner"] & JSXBase.HTMLAttributes<HTMLRuiMealPlannerElement>;
            /**
             * Modal dialog with default + footer slots.
             */
            "rui-modal": LocalJSX.IntrinsicElements["rui-modal"] & JSXBase.HTMLAttributes<HTMLRuiModalElement>;
            /**
             * Recipe card. Displays summary info and a favorite toggle.
             */
            "rui-recipe-card": LocalJSX.IntrinsicElements["rui-recipe-card"] & JSXBase.HTMLAttributes<HTMLRuiRecipeCardElement>;
            /**
             * Full recipe detail view: image, meta, ingredients, instructions.
             */
            "rui-recipe-detail": LocalJSX.IntrinsicElements["rui-recipe-detail"] & JSXBase.HTMLAttributes<HTMLRuiRecipeDetailElement>;
            /**
             * Responsive grid of recipe cards. Re-renders cards when recipes/favorites change.
             */
            "rui-recipe-list": LocalJSX.IntrinsicElements["rui-recipe-list"] & JSXBase.HTMLAttributes<HTMLRuiRecipeListElement>;
            /**
             * Search bar with debounced input + submit events.
             */
            "rui-search-bar": LocalJSX.IntrinsicElements["rui-search-bar"] & JSXBase.HTMLAttributes<HTMLRuiSearchBarElement>;
        }
    }
}
